

ratelimit:
  - appId: app-1
    limits:
      - api: /v1/user
        limit: 60
        unit: 60
      - api: /v1/order
        limit: 10
  - appId: app-2
    limits:
      - api: /v1/user
        limit: 10
        unit: 60
      - api: /v1/order
        limit: 5